server:
  port: 8765
spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://192.168.213.128:8888
  cloud:
    config:
      name: api_gateway
      uri: http://192.168.213.128:8888
    gateway:
      discovery:
        locator:
          enabled: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://192.168.213.128:8080/auth/realms/spring-boot-realm/protocol/openid-connect/token/introspect
          client-id: api-gateway
          client-secret: 4a78bb0b-988e-4bc8-8f7a-a32b66bbd321
eureka:
  instance:
    hostname: 192.168.213.128
  client:
    service-url:
      defaultZone: http://192.168.213.128:8761/eureka
resilience4j:
  retry:
    instances:
      sample-api:
        max-attempts: 5